import type { NextPage } from 'next';
import Head from 'next/head';
import Characters from '../components/Characters';

const Home: NextPage = () => {
	return (
		<main>
			<Head>
				<title>Rick and Morty Query</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<Characters />
		</main>
	);
};

export default Home;
